sudo: false
# dist: bionic
language: cpp

# branches:
#   only:
#     - master

env:
  global:
    - JOBS=4
    - PROJECT_NAME="mapbox-base"

jobs:
  - &test
    stage: test
    os: linux
    language: cpp
    name: Test / gcc-6-release
    cache:
      ccache: true
      apt: true
      directories:
        - test/cache
    addons: &gcc6
      apt:
        sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8' ]
        packages: ['g++-6']
    compiler: "gcc-6"
    env: "CCOMPILER='gcc-6' CXXCOMPILER='g++-6' BUILD_TYPE='Release'"
    install: scripts/ci/install-tests.sh
    script: scripts/ci/run-tests.sh

  - <<: *test
    name: Test / gcc-6-debug
    addons:
      apt:
        sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8' ]
        packages: ['g++-6']
    env: "CCOMPILER='gcc-6' CXXCOMPILER='g++-6' BUILD_TYPE='Debug'"
    install: scripts/ci/install-tests.sh
    script: scripts/ci/run-tests.sh
