name: Syntax Tests

on: push

jobs:
  test_syntax:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 16
        architecture:
          - x64

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: clang-format lint
        uses: DoozyX/clang-format-lint-action@v0.14
